apiVersion: v1alpha1
kind: ClusterValidator
metadata:
  name: conditions-validation
spec:
  configuration:
    # global test configuration
    successThreshold: 10
    failureThreshold: 10 
    interval: 1s
  resources:
    # resource name and apiVersion
  - name: nodes
    apiVersion: v1
    names:
      include: 
      - "*"
    # define the condition jsonpath, type and status
    conditions: 
    - path: status.conditions
      type: ready
      status: true
    # this validation is required in order for the test to succeed
    required: true
    configuration:
      # override the global configuration
      successThreshold: 5
      failureThreshold: 10
