apiVersion: v1alpha1
kind: ClusterValidator
metadata:
  name: field-validation
spec:
  configuration:
    successThreshold: 3
    failureThreshold: 3 
    interval: 1ms
  resources:
  - name: pods
    apiVersion: v1
    names:
      include: 
      - test-pod*
    namespaces:
      include:
      - test-namespace*
    fields: 
    - path: "{.status.containerStatuses[*].state.running.startedAt}"
    - path: "{.status.phase}"
      values:
      - running
      - succeeded
    required: true